baseURL = "http://localhost:1313/"
languageCode = "de"
defaultContentLanguage = "de"
title = "FichtelUltra"
theme = "themefu"

[params]
  description = "Ein Blog über Events und Abenteuer im Fichtelgebirge."
  titlePart1 = "Fichtel"
  titlePart2 = "Ultra"

[taxonomies]
  tag = "tags"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true # Ermöglicht das Rendern von raw HTML in Markdown (z.B. für Bilder)
