canonifyURLs = false
baseURL = "https://fichtelultra.de/"
languageCode = "de"
defaultContentLanguage = "de"
title = "FichtelUltra"
theme = "themefu"
disableKinds = ["taxonomy"]

[params]
  description = "Aus Freundschaft gewachsen, vom Fichtelgebirge inspiriert: FichtelUltra bringt Menschen zusammen, die gern draußen sind, wild träumen und weit laufen."
  titlePart1 = "Fichtel"
  titlePart2 = "Ultra"

[taxonomies]
  tag = "tags"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true # Ermöglicht das Rendern von raw HTML in Markdown (z.B. für Bilder)
