baseURL = 'https://fichtelultra.de/'
languageCode = 'de-DE'
title = 'FichtelUltra'
theme = 'futheme'

[params]
  homepageSections = ["about", "projects", "blog"]
  titlePart1 = "Fichtel"
  titlePart2 = "Ultra"